[package]
name = "test58_oauth"
version = "0.1.0"
authors = ["Pavel Ershov <devnulpavel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
actix-http = "2.2.0"
actix-service = "1.0.6"
actix-identity = "0.3.1"
actix-files = "0.5.0"
opentelemetry = "0.12.0"
opentelemetry-jaeger = "0.11.0"
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
tracing-appender = "0.1.2"
tracing-futures = "0.2.5"
tracing-actix-web = "0.2.1"
tracing-opentelemetry = "0.11.0"
futures = "0.3.13"
serde = "1.0.125"
serde_json = "1.0.64" 
serde_with = "1.7.0"
handlebars = "3.5.3"
quick-error = "2.0.0"
rand = "0.8.3"
url = "2.2.1"
lazy_static = "1.4.0"
clap = "2.33.3"
dotenv = "0.15.0"
tap = "1.0.1"
tracing-bunyan-formatter = {version = "0.2.0", default-features = false} # Отключаем, чтобы не было конфликта https://github.com/LukeMathWalker/tracing-bunyan-formatter/issues/3
uuid = { version = "0.8.2", features = ["v4"] }
reqwest = { version = "0.10.10", default-features = false, features = [ "json", "rustls-tls"] }
sqlx = { version = "0.4.2", features = [ "runtime-actix-rustls", "sqlite", "offline"] }