version: "3.3"
services:
    app:
        image: devnul/oauth_server
        container_name: oauth_server
        restart: always
        env_file:
            - credentials/test_environment_docker.env
        volumes:
            - $PWD/credentials:/oauth_server/credentials
            - $PWD/logs:/oauth_server/logs
            - $PWD/db:/oauth_server/db
        ports:
            - 8080:8080
    # network_mode: host