name: Build and publish
on:
    workflow_dispatch:
        branches:
            - main
jobs:
    deploy_on_server:
        runs-on: ubuntu-latest
        needs: build_and_push
        steps:
            - name: Deploy on server
              uses: appleboy/ssh-action@v0.1.3
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                script: |
                    cd web_platform_oauth/
                    docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
                    docker-compose stop
                    docker-compose rm -f
                    docker-compose pull
                    docker-compose up -d
